// <auto-generated />
using System;
using EFCodeFirstTask1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCodeFirstTask1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260515192222_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCodeFirstTask1.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "R75800X",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 2,
                            Description = "8-core, 16-thread desktop processor with 3.8 GHz base clock.",
                            Name = "AMD Ryzen 7 5800X"
                        },
                        new
                        {
                            Code = "RTX4090",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 3,
                            Description = "Ada Lovelace flagship GPU with 24 GB GDDR6X VRAM.",
                            Name = "NVIDIA GeForce RTX 4090"
                        },
                        new
                        {
                            Code = "DDR532G",
                            ComponentManufacturerId = 4,
                            ComponentTypeId = 1,
                            Description = "Single 32 GB DDR5 DIMM running at 6000 MT/s.",
                            Name = "Samsung 32 GB DDR5-6000"
                        },
                        new
                        {
                            Code = "990PRO2T",
                            ComponentManufacturerId = 4,
                            ComponentTypeId = 4,
                            Description = "PCIe 4.0 NVMe SSD with sequential read up to 7450 MB/s.",
                            Name = "Samsung 990 Pro 2 TB NVMe"
                        });
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateTime(1993, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "Intel",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices, Inc."
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Samsung",
                            FoundationDate = new DateTime(1969, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Samsung Electronics Co., Ltd."
                        });
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "CPU",
                            Name = "Central Proccesing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "GPU",
                            Name = "Graphics Proccesing Unit"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "Solid State Drive"
                        });
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasMaxLength(5)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "UltraDesk Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 8.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GamerRig X",
                            Stock = 7,
                            Warranty = 12,
                            Weight = 11.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "WorkStation Z",
                            Stock = 3,
                            Warranty = 36,
                            Weight = 14f
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CompactMini 500",
                            Stock = 20,
                            Warranty = 12,
                            Weight = 3.8f
                        });
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "R75800X",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "DDR532G",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RTX4090",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "990PRO2T",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "R75800X",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "990PRO2T",
                            Amount = 4
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "DDR532G",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "RTX4090",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.Component", b =>
                {
                    b.HasOne("EFCodeFirstTask1.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCodeFirstTask1.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.PCComponent", b =>
                {
                    b.HasOne("EFCodeFirstTask1.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCodeFirstTask1.Models.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("EFCodeFirstTask1.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
